version: '3.8'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: clinical_trials_db
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/bin/true"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  api:
    build:
      context: .
      dockerfile: ClinicalTrials.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ClinicalTrial;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
    depends_on:
      sqlserver:
        condition: service_healthy
volumes:
  sqldata: